version: '3.8'

services:

  load_balaner:
    image: nginx:alpine
    container_name: nginx_load_balancer
    ports:
      - "8080:80"
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - worker1
      - worker2
    networks:
      - app-network
    
  worker1:
    image: nginx:alpine
    container_name: nginx_worker_1
    volumes:
      - ./worker-1/html:/usr/share/nginx/html
    networks:
      - app-network

  worker2:
    image: nginx:alpine
    container_name: nginx_worker_2
    volumes:
      - ./worker-2/html:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge